### ISSUE TITLE
Video and html games play audio only no video content drawn on screen

### ISSUE THREAD

**Issue by tstr007** [xueqiya/AwDemo#1]
Thank you this this repo.
Video and html games black screen with audio only.
youtube as example.
I've already tried acceleration settings like hardware and software application level and activity level, but still no luck.
Is there something i miss ?
Thanks again for this repo.

**Comment by xueqiya** [comment]
Sorry, this repo does not currently support hardware acceleration

**Comment by tstr007** [comment]
hello.
I think this repo might help you.
if you're still looking for a better webview
https://github.com/shimohq/BisonView
Good Luck
